### ISSUE TITLE
AppleScript syntax errors in iterm automatic start osx script

### ISSUE THREAD

**Issue by yevgenykuz** [tmux-plugins/tmux-continuum#111]
When using on of the following options:
* set -g @continuum-boot-options 'iterm'
* set -g @continuum-boot-options 'iterm,fullscreen'

The following syntax errors prevent from auto-start script to run in iterm:
* 102:110: syntax error: Expected end of line but found identifier. (-2741)
* 60:64: syntax error: Expected end of line but found identifier. (-2741)
* 155:159: syntax error: Expected end of line but found identifier. (-2741)

Iterm version - Build 3.4.16

**Comment by bruno-** [comment]
This should be fixed with #112
