### ISSUE TITLE
Continuum status brakes the moving around panes with hjkl

### ISSUE THREAD

**Issue by ubermensh** [tmux-plugins/tmux-continuum#29]
got this in my tmux.conf:

```
# move around panes with hjkl, as one would in vim after pressing ctrl-w
 bind h select-pane -L
 bind j select-pane -D
 bind k select-pane -U
 bind l select-pane -R
```

but it did not work. figured out that this line is the cause:
`set -g status-right 'Continuum status: #{continuum_status}'`
after commenting it out, it works fine.

**Comment by PrgrmAtCeleritas** [comment]
I wonder if [this](https://github.com/tmux-plugins/tmux-copycat/pull/88/files) has anything to do with it

**Comment by bruno-** [comment]
Hey, I think this plugin should not be affecting key bindings... It could be it's related to tmux-copycat.
