### ISSUE TITLE
Maximum number of snaphot files feature

### ISSUE THREAD

**Issue by LukaK** [tmux-plugins/tmux-continuum#32]
Hi,
first thank you for the plugin.

It doesn't seem to an option to rotate files or to add max number of files in resurrect folder.
Current solution for dealing with the problem of too many snapshots is periodically cleaning the directory by hand or by writing cron jobs.

Do you have any plans of adding some kind of self management in the future?

**Comment by bruno-** [comment]
Hey tmux-resurrect automatically deletes backups older than 30 days

https://github.com/tmux-plugins/tmux-resurrect/blob/6feae65a836c76b0b48a24959a59ff4040d09f16/scripts/save.sh#L271

I think the feature was implemented after this issue was opened.
