### ISSUE TITLE
${HOME}/.config/systemd/user/tmux.service Not creating automatically.

### ISSUE THREAD

**Issue by razcakappa** [tmux-plugins/tmux-continuum#37]
Even after insert @continuum-boot is set to 'on'
${HOME}/.config/systemd/user/tmux.service
Not creating automatically. 
Using Ubuntu 16.04

**Comment by bruno-** [comment]
Hey, I'm not sure what's the current working status of `@continuum-boot` on Linux. I'm on macOS and I make sure that one works..
Someone else want to look into how to make this work on Linux?

**Comment by razcakappa** [comment]
@bruno- Can you paste here your `.config/systemd/user/tmux.service ` file? 
May be I could manually place that and see.

**Comment by bruno-** [comment]
Hey,
as mentioned above, I don't use Linux (as a personal computer) so I don't have a systemd file for it.

All the startup related files this plugin has are in this directory: https://github.com/tmux-plugins/tmux-continuum/tree/master/scripts/handle_tmux_automatic_start. There are 2 systemd files there, but I don't know how well they work.

**Comment by bruno-** [comment]
Sorry I can't be of more help. When I initially developed this feature I was perplexed with the complexity of this on Linux.. All the contributions for Linux were made by other.

Please feel free to get proactive on this and submit changes/additions if you figure out how to improve things.

**Comment by neynt** [comment]
This is probably because `systemd_enable.sh` doesn't create the directory `~/.config/systemd/user` if it doesn't already exist. I submitted a pull request to fix this.

**Comment by bruno-** [comment]
Thank you @neynt , I merged your PR and will close this issue. I have no means of really verifying if this fixes it so please reopen the issue if this is still a problem.

**Comment by switz** [comment]
On my raspberry pi the directory is created, but empty. Any ideas?
