### ISSUE TITLE
Restore not working on Linux / tmux 1.9-6

### ISSUE THREAD

**Issue by GuillaumeSeren** [tmux-plugins/tmux-continuum#5]
Hi there,
I've just discovered your work, last week and seriously thank you it is awesome !

I find the idea great, and most of the plugin where most wanted features in tmux for long time,
specially, a way of make tmux, survive reboot, so I ended installing continuum.

But even if I add the auto restore the session didn't come back, here some details:

I use tmuxinator to design the session content, (https://github.com/tmuxinator/tmuxinator)
and it is also used to launch tmux itself, by .Xsessionrc:

    urxvtcd -e bash -c 'echo "--> Get Screen session central" &&
    tmuxinator start central ' &

After that my revelant part of my ~/.tmux.conf 

    # List of plugins
    # Supports `github_username/repo` or full git repo URLs
    set -g @tpm_plugins '              \
      tmux-plugins/tpm                 \
      tmux-plugins/tmux-sensible       \
      tmux-plugins/tmux-copycat        \
      tmux-plugins/tmux-resurrect      \
      tmux-plugins/tmux-continuum      \
      tmux-plugins/tmux-yank           \

    # Plugin conf
    set -g @continuum-restore 'on'

    # Other examples:
    # github_username/plugin_name    \
    # git@github.com/user/plugin     \
    # git@bitbucket.com/user/plugin  \

    # Initializes TMUX plugin manager.
    # Keep this line at the very bottom of tmux.conf.
    run-shell '~/.tmux/plugins/tpm/tpm'

Any idea / test to make it work ?

Guillaume.

**Comment by bruno-** [comment]
Hey,
sorry for the late response. Did you have any luck with this?

Frankly I'm not sure how well this plugin works with `tmuxinator`. I think they both try to do the same thing with different approaches, that is: create tmux environment.

Did you try using `tmux-resurrect` on it's own? Is that working ok?

**Comment by GuillaumeSeren** [comment]
Hey @bruno- thank you for responding :+1: 
again thank you for your work it is a really good and needed projects for tmux users.

So on this issue, I still don't fix it but it is not a big pain because tmuxinator give a good preset in the session, on this point it near but keeping the session saved on top of tmuxinator would be great.

I will upgrade and check the whole process again then update my status here.

**Comment by bruno-** [comment]
As mentioned previously, you might experience some collision between tmuxinator and tmux-resurrect because they both do the same job. It might make sense to pick one and just stick with it.

Anyhow, if you do the experiment of running both together, please update this thread with your findings. Thanks!

**Comment by GuillaumeSeren** [comment]
Yes I understand that, but I feel tmuxinator can provide a default state and tmux-continuum,
a saved-session so we can just test if there is a saved session and in this case load, on top of tmuxinator.

I will take some time to make test, and give back details here.

**Comment by bruno-** [comment]
Any updates on this?

**Comment by GuillaumeSeren** [comment]
Hi @bruno- ,
I have not been able to gather much time on this task, but I made some test out of tmuxinator session,
I will publish a summary of my test soon.

Guillaume.

**Comment by bruno-** [comment]
Hi,
I made a short doc about moving to `tmux-resurrect` from `tmuxinator`, pros and cons etc. Here's the [link](https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/migrating_from_tmuxinator.md).

It would be good to get some feedback on this issue so we can either fix or close it.

**Comment by GuillaumeSeren** [comment]
Hi Bruno,
yes I was missing time to do that and I have seen your doc on migrating from 'tmuxinator' to 'tmux-resurrect', I did not want to stay with tmuxinator anymore, too much dependencies.

I think this issue can be close.

Again thank for your work ! :)

Guillaume.

**Comment by bruno-** [comment]
Thanks!
