### ISSUE TITLE
Automatic restore not working

### ISSUE THREAD

**Issue by mike182uk** [tmux-plugins/tmux-continuum#57]
Howdy!

I see recently there was a fix for automatic restore not working in OSX (https://github.com/tmux-plugins/tmux-continuum/issues/52).

I'am actually finding that this has broken automatic restore for me on macOS (Mojave - 10.14.3). When i start `tmux` nothing is restored. Interestingly, if i reload my config, the restore then happens (which shouldn't happen according to [this](https://github.com/tmux-plugins/tmux-continuum#automatic-restore))

If i revert the changes made [here](https://github.com/tmux-plugins/tmux-continuum/commit/4e2279688d8a577ed14f42c4e8af1acb58100a57) everything seems to be working ok for me.

I'am using `tmux 2.8` and the latest versions of `tmux-continuum` and `tmux-resurrect`

**Comment by Kriechi** [comment]
auto-close didn't work - please close due to #58

**Comment by bruno-** [comment]
Closing because #58 was merged.
