### ISSUE TITLE
Autosave interrupts when I'm typing commands in bash

### ISSUE THREAD

**Issue by davidjb** [tmux-plugins/tmux-continuum#6]
I've got continuum & resurrect installed in my tmux (version 1.9) and it's great (thanks!). 

I've encountered an issue that if I'm typing a command and the save interval rolls around, my command is interrupted; with the ``history -w ...`` command being injected into the terminal.  What I was typing is thus cut off, and I'm presented with an empty prompt.  

My settings are:
```
set -g @continuum-restore 'on'
set -g @continuum-save-interval '60'
```
which I suppose means there's a chance every hour for this to happen, if I'm typing or have left a command waiting to be run on the terminal.

I'm using the latest version of the plugin from Git at time of writing and stock Bash on Ubuntu 15.04 as my shell.

**Comment by bruno-** [comment]
Hey,
do you by any chance have `set -g @resurrect-save-bash-history 'on'`? (an experimental feature from tmux-resurrect plugin)

When that feature is turned on, it does what you describe (inserts `history -w..`).
So, try fixing this by setting the save bash history feature to off. For example, just do

    $ tmux set -g @resurrect-save-bash-history 'off'

in the terminal and the issue should not happen on next save cycle.

Frankly, I find the save bash history feature obnoxious and I'm even thinking of removing it from tmux-resurrect altogether.

**Comment by davidjb** [comment]
Yes, sorry forgot to mention that option's enabled.  I was slightly dubious about not having the history saved, but on balance, my tmux session and computer rarely get restarted anyway so turning this off won't be as big an issue as I'd first thought.

Out of interest, why do you consider the history feature obnoxious?

**Comment by bruno-** [comment]
Hey, okay cool!

I dislike the history feature because it's not clean. In both the save and restore steps it sends commands to the working panes (what you experienced). This changes what the user sees and interrupts the workflow. From what I know no other option is that intrusive.

But hey, maybe it's just me.

**Comment by davidjb** [comment]
I very much agree; I could accept the occasional interjection of the save/restore commands as a once off but on a repeated basis, it's a real pain. 

Could you do something like changing Bash's [$PROMPT_COMMAND](http://northernmost.org/blog/flush-bash_history-after-each-command/) to save after each command into the pane history file? Or perhaps manipulate Bash's $HISTFILE (on shell startup) to point the specific file for each pane?  Not sure manipulating environment variables like this is feasible in tmux, but changing the ``.bashrc`` to reference a tmux-specific function would seemingly be an option.

**Comment by bruno-** [comment]
Hey @davidjb,
I'd accept a pull request to tmux-resurrect that improves the "quality" of this feature..
I personally don't feel very motivated to work on this as I don't use the feature. If there's help needed I'll be glad to help though.

**Comment by bruno-** [comment]
We have this issue logged in [tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect/issues/86). As this issue is more related to that project, I'll leave that one open and close this.
