### ISSUE TITLE
[Bug] Pane command history (bash history) is not saved/restored 

### ISSUE THREAD

**Issue by arderyp** [tmux-plugins/tmux-continuum#67]
I am not sure if this is a continuum or a [resurrect](https://github.com/tmux-plugins/tmux-resurrect/issues/310) issue)

Am I missing a configuration somewhere?

I have 5 panes set up in my session, and I have the following config:

```
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/resurrect'
set -g @plugin 'tmux-plugins/continuum'

# Enable autorestore
set -g @continuum-restore 'on'

# Save session every 5 minutes
set -g @continuum-save-interval '1'

# Save shell history (THIS IS BROKEN)
#set -g @resurrect-save-shell-history 'on'

# Save pane contents
set -g @resurrect-capture-pane-contents 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
```

When I reboot, then run `tmux`, my last session of 5 panes is restored.  I even see the outputs in each pane as they appeared before reboot.  However, when I navigate through each pane and use the up arrow key to re-run the most recently run command in said pane, the command is incorrect.  In fact, they all show the same command (the last command I executed in any terminal session, anywhere, before reboot).  So, if I rebooted from the command line with `sudo reboot`, the last command (hitting up arrow once) in each pane is `sudo reboot`.

I must be missing something, right?  I've tried lots of googling and combing through issues here to no avail. Thanks in advance for the help.

**Comment by schmoelder** [comment]
I have the same issue.

**Comment by arderyp** [comment]
bash history is deprecated an either already removed, or on its way out the door, according to @bruno- [here](https://github.com/tmux-plugins/tmux-resurrect/issues/310#issuecomment-678728543)
