### ISSUE TITLE
[Docs] Autosave feature depends on TPM plugins order

### ISSUE THREAD

**Issue by nivnadler** [tmux-plugins/tmux-continuum#81]
In order to be executed periodically, the plugin updates the `status-right` tmux variable. This way it is executed every `15` seconds (default update time for `status-right`). In case some plugin (usually themes) overwrites the `status-right` variable, the autosave feature stops working. To fix this issue, place the plugin last in the TPM plugins list. This is a crucial information that must be added to the README file.

**Comment by bruno-** [comment]
You're right. Feel free to open a PR.

It would be ideal if we could come up with a way to update `status-right` AFTER theme plugins do their job.
